### PR TITLE
fix comments in dokblocks

### LINKED ISSUE #779: Pest v2 fails to build the tests where the name contains /** comment */ syntax.
In Pest v1 I had a test name with `/** @typescript */` in the name which worked fine:

```
test('all value objects have the /** @typescript */ hint for our frontend structs', function (string $path) {
    ...
})->with('value objects paths');
```

In Pest v2, I needed to remove the `/**` and `*/` parts of the test name, else I get this error:

<details><summary>Error:</summary>

```
   ERROR  Unable to create test case for test file at /.../tests/Feature/ValueObjectsShouldHaveTypescriptHintTest.php.

 namespace P\Tests\Feature;

use Pest\Repositories\DatasetsRepository as __PestDatasets;
use Pest\TestSuite as __PestTestSuite;

/**
 * @testdox /.../tests/Feature/ValueObjectsShouldHaveTypescriptHintTest.php
 */

#[\AllowDynamicProperties]
final class ValueObjectsShouldHaveTypescriptHintTest extends \Tests\TestCase implements \Pest\Contracts\HasPrintableTestCaseName {
    use \Pest\Concerns\Testable, \Pest\Concerns\Expectable, \Pest\Arch\Concerns\Architectable, \Worksome\RequestFactories\Concerns\Pest\FakesRequests;

    private static $__filename = '/.../tests/Feature/ValueObjectsShouldHaveTypescriptHintTest.php';

    
    /**
     * @test
     * @testdox all value objects have the /** @typescript */ docblock hint for our frontend structs
     * @dataProvider __pest_evaluable_all_value_objects_have_the______typescript____docblock_hint_for_our_frontend_structs_dataset
     */
    
    public function __pest_evaluable_all_value_objects_have_the______typescript____docblock_hint_for_our_frontend_structs()
    {
        $test = \Pest\TestSuite::getInstance()->tests->get(self::$__filename)->getMethod($this->name())->getClosure($this);

        return $this->__runTest(
            $test,
            ...func_get_args(),
        );
    }
    
        public static function __pest_evaluable_all_value_objects_have_the______typescript____docblock_hint_for_our_frontend_structs_dataset()
        {
            return __PestDatasets::get(self::$__filename, "__pest_evaluable_all_value_objects_have_the______typescript____docblock_hint_for_our_frontend_structs");
        }

    /**
     * @test
     * @testdox all value objects should have `Value.php` appended to the file name
     * @dataProvider __pest_evaluable_all_value_objects_should_have__Value_php__appended_to_the_file_name_dataset
     */
    
    public function __pest_evaluable_all_value_objects_should_have__Value_php__appended_to_the_file_name()
    {
        $test = \Pest\TestSuite::getInstance()->tests->get(self::$__filename)->getMethod($this->name())->getClosure($this);

        return $this->__runTest(
            $test,
            ...func_get_args(),
        );
    }
    
        public static function __pest_evaluable_all_value_objects_should_have__Value_php__appended_to_the_file_name_dataset()
        {
            return __PestDatasets::get(self::$__filename, "__pest_evaluable_all_value_objects_should_have__Value_php__appended_to_the_file_name");
        }

}
Location: /.../vendor/pestphp/pest/src/Factories/TestCaseFactory.php:198

#0 /.../vendor/pestphp/pest/src/Factories/TestCaseFactory.php(88): Pest\Factories\TestCaseFactory->evaluate('/Users/adrianbr...', Array)
#1 /.../vendor/pestphp/pest/src/Repositories/TestRepository.php(199): Pest\Factories\TestCaseFactory->make()
#2 /.../vendor/pestphp/pest/src/Repositories/TestRepository.php(156): Pest\Repositories\TestRepository->make(Object(Pest\Factories\TestCaseFactory))
#3 /.../vendor/pestphp/pest/overrides/Runner/TestSuiteLoader.php(85): Pest\Repositories\TestRepository->makeIfNeeded('/Users/adrianbr...')
#4 /.../vendor/pestphp/pest/overrides/Runner/TestSuiteLoader.php(86): PHPUnit\Runner\TestSuiteLoader::PHPUnit\Runner\{closure}()
#5 /.../vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(89): PHPUnit\Runner\TestSuiteLoader->load('/Users/adrianbr...')
#6 /.../vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(46): PHPUnit\TextUI\Configuration\TestSuiteBuilder->testSuiteFromPath('/Users/adrianbr...', Array)
#7 /.../vendor/phpunit/phpunit/src/TextUI/Application.php(305): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\Configuration\Configuration))
#8 /.../vendor/phpunit/phpunit/src/TextUI/Application.php(101): PHPUnit\TextUI\Application->buildTestSuite(Object(PHPUnit\TextUI\Configuration\Configuration))
#9 /.../vendor/pestphp/pest/src/Kernel.php(86): PHPUnit\TextUI\Application->run(Array)
#10 /.../vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle(Array)
#11 /.../vendor/pestphp/pest/bin/pest(99): {closure}()
#12 {main}

Caused by: /.../vendor/pestphp/pest/src/Factories/TestCaseFactory.php(196) : eval()'d code:19

#0 /.../vendor/pestphp/pest/src/Factories/TestCaseFactory.php(88): Pest\Factories\TestCaseFactory->evaluate('/Users/adrianbr...', Array)
#1 /.../vendor/pestphp/pest/src/Repositories/TestRepository.php(199): Pest\Factories\TestCaseFactory->make()
#2 /.../vendor/pestphp/pest/src/Repositories/TestRepository.php(156): Pest\Repositories\TestRepository->make(Object(Pest\Factories\TestCaseFactory))
#3 /.../vendor/pestphp/pest/overrides/Runner/TestSuiteLoader.php(85): Pest\Repositories\TestRepository->makeIfNeeded('/Users/adrianbr...')
#4 /.../vendor/pestphp/pest/overrides/Runner/TestSuiteLoader.php(86): PHPUnit\Runner\TestSuiteLoader::PHPUnit\Runner\{closure}()
#5 /.../vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(89): PHPUnit\Runner\TestSuiteLoader->load('/Users/adrianbr...')
#6 /.../vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(46): PHPUnit\TextUI\Configuration\TestSuiteBuilder->testSuiteFromPath('/Users/adrianbr...', Array)
#7 /.../vendor/phpunit/phpunit/src/TextUI/Application.php(305): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\Configuration\Configuration))
#8 /.../vendor/phpunit/phpunit/src/TextUI/Application.php(101): PHPUnit\TextUI\Application->buildTestSuite(Object(PHPUnit\TextUI\Configuration\Configuration))
#9 /.../vendor/pestphp/pest/src/Kernel.php(86): PHPUnit\TextUI\Application->run(Array)
#10 /.../vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle(Array)
#11 /.../vendor/pestphp/pest/bin/pest(99): {closure}()
#12 {main}.
```

</details>

### PR DESCRIPTION
**Pull request by fabio-ivona**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| Fixed tickets | #779

### CODE REVIEW

File: tests/Unit/TestName.php [hunk 1]
```diff
@@ -61,12 +61,14 @@
...
 ];
 
 foreach ($names as $name => $methodName) {
     test($name)
         ->expect(fn () => static::getLatestPrintableTestCaseMethodName())
         ->toBe($name)
         ->and(fn () => $this->name())
-        ->toBe($methodName);
+        ->toBe($methodName)
+        ->only();
```
Comment (owenvoke) [inline tests/Unit/TestName.php]: Is `only()` meant to be here?

Comment (fabio-ivona) [reply tests/Unit/TestName.php]: Damn, forgot it 🤦

**Review by owenvoke — APPROVED** [review]
