### PR TITLE
fix: nested dataset discovery and parallel invalid-dataset reporting

### LINKED ISSUE #1121: [Bug]: Cannot use Datasets in subfolders
### What Happened

As part of my transition from Laravel 9 to Laravel 10, I am also upgrading from Pest 1.x to 2.x. During this process, I encountered an issue concerning the resolution of datasets located within subfolders.

I'm not the only one with this problem, please refer to [laracast question] for more details. (https://laracasts.com/discuss/channels/testing/pest-global-datasets-not-allowed-in-modular-project)

### How to Reproduce

Construct a dataset and place it within a subfolder inside the Datasets directory. Afterwards, execute the command `./vendor/bin/pest MyTest.php`, which unfortunately results in a failure.

However, this situation is peculiar as executing the test through PHPStorm does not present any issues, indicating that the problem only occurs when running the test from the terminal...

### Sample Repository

_No response_

### Pest Version

2.34.4

### PHP Version

8.2.16

### Operation System

macOS

### Notes

_No response_

### PR DESCRIPTION
**Pull request by stsepelin**
### What:

- [x] Bug Fix
- [ ] New Feature

### Description:

This PR follows up on #1427 and fixes two related problems in Pest's parallel execution flow.

First, it fixes nested dataset discovery for datasets stored in nested `Datasets/` directories, addressing #1121.

Second, it fixes parallel reporting when a dataset is invalid or missing, so these cases are surfaced correctly as failures rather than being lost in the summary, addressing #1185.

The PR also adds regression coverage for both scenarios and keeps the success snapshot coverage in place with a lower memory limit for the visual snapshot test.

### Related:

- Fixes #1121
- Refs #1185
- Follow-up to #1427

### CODE REVIEW

File: tests/Visual/Success.php [hunk 1]
```diff
@@ -12,7 +12,7 @@
 
     $output = function () use ($testsPath) {
         $process = (new Process(
-            ['php', 'bin/pest'],
+            ['php', '-d', 'memory_limit=256M', 'bin/pest'],
```
Comment (stsepelin) [inline tests/Visual/Success.php:15]: I'm not quite sure about this change. After the snapshots.txt update, the default PHP config (128M memory limit)  started failing with memory limit warnings.

**Comment by thomas-0816** [comment]
Thank You!
I guess the changes in src/Support/StateGenerator.php should fix https://github.com/pestphp/pest/issues/1462 and https://github.com/pestphp/pest/issues/1463 .

@stsepelin Should these methods from https://github.com/sebastianbergmann/phpunit/blob/main/src/Runner/TestResult/TestResult.php also be handled in src/Support/StateGenerator.php ?
- public function testRunnerTriggeredDeprecationEvents() // added in phpunit 12
- public function testRunnerTriggeredNoticeEvents() // added in phpunit 12
- public function testRunnerTriggeredWarningEvents() // added in phpunit 12
- public function testSuiteSkippedEvents()
- public function errors()

**Comment by nunomaduro** [comment]
@thomas-0816 all of them.

**Comment by stsepelin** [comment]
Thanks for the merge! 

Opened a follow-up PR to handle the remaining `PHPUnit\TestRunner\TestResult\TestResult` methods you mentioned
(`testRunnerTriggered{Deprecation,Notice,Warning}Events`, `testSuiteSkippedEvents`, `errors`): #1683.

That also covers the "missing implementations in StateGenerator.php"
part of #1462.
